### ISSUE TITLE
New default egress rules 

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/OpenShift4-Migration#38]
OCP4 is in the SDN Compartment, and uses Secure Internet Service Firewall that does do some filtering and IPS.  For example, `tcp/9700:9799` no longer works (by default).

Example spec:
```yaml
spec:
  description: allow my namespace namespace to talk to the internet.
  destination:
    - - 'ext:network=any'
  source:
    - - $namespace=<mynamespace>-dev
```

RocketChat Reference(s):
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=pqAet6NH3mi5hJGKE
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=NRAcjxnooeoBsaAme
- https://chat.pathfinder.gov.bc.ca/channel/devops-ocp4-migration?msg=vpe9Qced2WM4Tp3BC

For further details:
If this egress is required, you may submit a firewall request with the source `MCS-SILVER-NAT` and just mention Secure Internet Service Firewall to:
- https://ssbc-client.gov.bc.ca/order/howtoorder.htm
- https://ssbc-client.gov.bc.ca/services/Firewall/order.htm
