### ISSUE TITLE
Cannot provide jenkins service account with permission to image pull & build on dev namespace

### ISSUE THREAD

**Issue by ajdeziel** [BCDevOps/OpenShift4-Migration#67]
I have been attempting to build & deploy using the `jenkins` service account from my `tools` namespace into my `dev` namespace. However, I keep encountering this error when pulling in base images from my `tools` namespace into `dev`:

```none
Pulling image image-registry.openshift-image-registry.svc:5000/9c33a9-tools/aspnet:3.1 ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: unauthorized: authentication required
error: the build 9c33a9-dev/dotnet-webapi-develop-temp-ocp4-9 status is "Failed"
```

To resolve this, I tried to perform the following with no success:
* Provide the service account with the `system:image-puller` and `system:image-builder` role binding in my `dev` namespace.
* Ensuring that the NSPs across `dev` and `tools` are able to talk with one another.

**Comment by StevenBarre** [comment]
1. Shouldn't builds be happening in `9c33a9-tools` ?
2. The `jenkins` SA interacts with the BuildConfig objects to trigger new builds, but the builds themselves run as the `builder` SA.
3. So the service account `9c33a9-dev/builder` needs `system:image-puller` RoleBinding in `9c33a9-tools`

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-image-puller
  namespace: 9c33a9-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: builder
  namespace: 9c33a9-dev
- kind: ServiceAccount
  name: builder
  namespace: 9c33a9-test
- kind: ServiceAccount
  name: builder
  namespace: 9c33a9-prod
```

/cc @jleach in case I missed anything
